### ISSUE TITLE
Билдится с ошибкой

### ISSUE THREAD

**Issue by asci** [bem-node/bem-node-hello-world#1]
$ make
rm -f `find ./app/*/* ! -name '*bemdecl.js'`
npm install
npm WARN package.json bem-node-hello-world@0.0.1 No description
npm WARN package.json bem-node-hello-world@0.0.1 No repository field.
./node_modules/enb/bin/enb make
19:26:47.623 - build started
19:26:48.021 - [rebuild] [app/example/example.bemdecl.js] file-provider
19:26:48.021 - [rebuild] [app/example/example.levels] levels
19:26:48.073 - [rebuild] [app/example/example.deps.js] deps-old
19:26:48.074 - [rebuild] [app/example/example.files] files
19:26:48.074 - [rebuild] [app/example/example.dirs] files
19:26:48.080 - [app/example] Calm down, OmetaJS is running...
19:26:48.086 - [rebuild] [app/example/example.css] css-includes
19:26:48.086 - [rebuild] [app/example/example.priv.js] priv.js
19:26:48.086 - [rebuild] [app/example/example.server.js] server.js
19:26:48.086 - [rebuild] [app/example/example.tests.js] tests.js

undefined:1
 P4P; toString = Object.prototype.toString,\n    SHORT_TAGS = { // QQ
                                                                    ^
SyntaxError: Unexpected token 
    at Object.parse (native)
    at Pipe.channel.onread (child_process.js:335:28)

**Comment by asci** [comment]
При попытке посетить 127.0.0.1:3000

Error node_modules/bem-node/blocks/i-response/i-response.priv.js:91 
ReferenceError: BEMHTML is not defined
    at /Users/slvrnight/Projects/meetmefor/node_modules/bem-node/blocks/i-content/_type/i-content_type_bemhtml.common.js:35:37
    at Object.thread.callback (/Users/slvrnight/Projects/meetmefor/node_modules/bem-node/node_modules/bem-json/i-bem/__json/_async/i-bem__json_async_yes.js:126:17)
    at Object.BEM.JSON.buildAsync (/Users/slvrnight/Projects/meetmefor/node_modules/bem-node/node_modules/bem-json/i-bem/__json/_async/i-bem__json_async_yes.js:134:20)
    at Function.BEM.decl._htmlAsync (/Users/slvrnight/Projects/meetmefor/node_modules/bem-node/blocks/i-content/_type/i-content_type_bemhtml.common.js:32:22)
    at /Users/slvrnight/Projects/meetmefor/node_modules/bem-node/blocks/i-content/_type/i-content_type_bh.common.js:12:20
    at /Users/slvrnight/Projects/meetmefor/node_modules/bem-node/node_modules/vow/lib/vow.js:184:31
    at process._tickDomainCallback (node.js:459:13)

**Comment by delfrrr** [comment]
Еще актуально?

**Comment by asci** [comment]
Да
